// City data for programmatic SEO page generation
// All cities in Spain organized by province

// ALL CITIES IN SPAIN organized by region and province
export const CITIES_SPAIN: Record<string, string[]> = {
  // ============ CATALUNYA ============
  barcelona: [
    "barcelona",
    "hospitalet-llobregat",
    "badalona",
    "terrassa",
    "sabadell",
    "mataro",
    "santa-coloma-gramenet",
    "cornella-llobregat",
    "sant-boi-llobregat",
    "sant-cugat-valles",
    "rubi",
    "vilanova-geltru",
    "viladecans",
    "prat-llobregat",
    "castelldefels",
    "granollers",
    "cerdanyola-valles",
    "mollet-valles",
    "gava",
    "esplugues-llobregat",
    "sant-feliu-llobregat",
    "ripollet",
    "sant-adria-besos",
    "montcada-reixac",
    "vic",
    "igualada",
    "vilafranca-penedes",
    "manresa",
    "sant-vicenc-dels-horts",
    "premia-mar",
    "sitges",
    "el-masnou",
    "martorell",
    "sant-pere-ribes",
    "sant-andreu-barca",
    "pineda-mar",
    "barbera-valles",
    "calella",
    "molins-rei",
    "cardedeu",
    "berga",
    "caldes-montbui",
    "llinars-valles",
    "palau-solita-plegamans",
    "montornes-valles",
    "la-garriga",
    "parets-valles",
    "sant-quirze-valles",
    "tordera",
    "arenys-mar",
    "canet-mar",
    "sant-celoni",
    "malgrat-mar",
    "santa-perpetua-mogoda",
    "argentona",
    "cubelles",
    "castellar-valles",
    "sant-sadurni-anoia",
    "olesa-montserrat",
    "abrera",
    "badia-valles",
    "begues",
    "cabrera-mar",
    "cabrils",
    "calaf",
    "canovelles",
    "capellades",
    "cardona",
    "centelles",
    "cervello",
    "corbera-llobregat",
    "esparreguera",
    "gelida",
    "gironella",
    "la-llagosta",
    "les-franqueses-valles",
    "manlleu",
    "masquefa",
    "montmelo",
    "navarcles",
    "palleja",
    "papiol",
    "piera",
    "polinya",
    "sallent",
    "sant-joan-despi",
    "sant-just-desvern",
    "santpedor",
    "teia",
    "tiana",
    "tona",
    "torello",
    "torrelles-llobregat",
    "vacarisses",
    "vallirana",
    "vilassar-dalt",
    "vilassar-mar",
    "mongat",
    "castellbisbal",
    "sant-pol-mar",
  ],
  girona: [
    "girona",
    "figueres",
    "blanes",
    "lloret-mar",
    "olot",
    "salt",
    "palafrugell",
    "sant-feliu-guixols",
    "roses",
    "banyoles",
    "palamos",
    "la-bisbal-emporda",
    "torroella-montgri",
    "castello-empuries",
    "calonge-sant-antoni",
    "lescala",
    "santa-coloma-farners",
    "arbucies",
    "cassa-selva",
    "llagostera",
    "platja-aro",
    "puigcerda",
    "ripoll",
    "ribes-freser",
    "camprodon",
    "besalu",
    "angles",
    "amer",
    "celra",
    "hostalric",
    "llança",
    "pals",
    "peralada",
    "portbou",
    "sils",
    "tossa-mar",
    "vidreres",
    "cadaques",
    "empuriabrava",
    "caldes-malavella",
  ],
  tarragona: [
    "tarragona",
    "reus",
    "tortosa",
    "salou",
    "cambrils",
    "vila-seca",
    "valls",
    "vendrell",
    "amposta",
    "calafell",
    "cunit",
    "torredembarra",
    "altafulla",
    "sant-carles-rapita",
    "deltebre",
    "montblanc",
    "ulldecona",
    "roquetes",
    "mora-ebre",
    "alcanar",
    "constanti",
    "la-selva-camp",
    "riudoms",
    "mont-roig-camp",
    "creixell",
    "roda-bera",
    "les-borges-camp",
    "falset",
    "gandesa",
    "alcover",
    "arbos",
    "miami-platja",
  ],
  lleida: [
    "lleida",
    "balaguer",
    "tarrega",
    "mollerussa",
    "la-seu-urgell",
    "cervera",
    "almacelles",
    "alpicat",
    "tremp",
    "solsona",
    "ponts",
    "agramunt",
    "les-borges-blanques",
    "bellpuig",
    "guissona",
    "vielha",
    "sort",
    "alfarras",
    "almenar",
    "artesa-segre",
    "juneda",
    "bellver-cerdanya",
    "el-pont-suert",
    "la-pobla-segur",
  ],

  // ============ COMUNIDAD DE MADRID ============
  madrid: [
    "madrid",
    "mostoles",
    "alcala-henares",
    "fuenlabrada",
    "leganes",
    "getafe",
    "alcorcon",
    "torrejon-ardoz",
    "parla",
    "alcobendas",
    "las-rozas",
    "san-sebastian-reyes",
    "pozuelo-alarcon",
    "coslada",
    "rivas-vaciamadrid",
    "valdemoro",
    "majadahonda",
    "collado-villalba",
    "aranjuez",
    "arganda-rey",
    "boadilla-monte",
    "pinto",
    "colmenar-viejo",
    "tres-cantos",
    "san-fernando-henares",
    "galapagar",
    "arroyomolinos",
    "navalcarnero",
    "ciempozuelos",
    "villanueva-pardillo",
    "villaviciosa-odon",
    "torrelodones",
    "mejorada-campo",
    "humanes-madrid",
    "paracuellos-jarama",
    "algete",
    "moralzarzal",
    "villanueva-canada",
    "san-martin-valdeiglesias",
    "chinchon",
    "guadarrama",
    "el-escorial",
    "san-lorenzo-escorial",
    "alpedrete",
    "brunete",
    "sevilla-nueva",
    "villalbilla",
    "meco",
    "daganzo-arriba",
    "cercedilla",
    "navacerrada",
    "loeches",
    "torrejon-velasco",
    "san-martin-vega",
    "torres-alameda",
    "ajalvir",
    "fuente-el-saz",
    "pedrezuela",
    "guadalix-sierra",
    "soto-real",
    "el-molar",
    "talamanca-jarama",
    "cubas-sagra",
    "becerril-sierra",
    "el-boalo",
    "manzanares-real",
    "los-molinos",
    "collado-mediano",
  ],

  // ============ ANDALUCIA ============
  malaga: [
    "malaga",
    "marbella",
    "mijas",
    "velez-malaga",
    "fuengirola",
    "torremolinos",
    "benalmadena",
    "estepona",
    "rincon-victoria",
    "antequera",
    "alhaurin-torre",
    "alhaurin-grande",
    "coin",
    "nerja",
    "torrox",
    "cartama",
    "ronda",
    "manilva",
    "alora",
    "pizarra",
    "campillos",
    "mollina",
    "archidona",
    "alameda",
    "casabermeja",
    "colmenar",
    "frigiliana",
    "competa",
    "algarrobo",
    "torre-mar",
    "benahavis",
    "ojen",
    "istan",
    "casares",
    "gaucin",
    "san-pedro-alcantara",
    "monda",
    "puerto-banus",
  ],
  sevilla: [
    "sevilla",
    "dos-hermanas",
    "alcala-guadaira",
    "utrera",
    "mairena-aljarafe",
    "ecija",
    "los-palacios-villafranca",
    "la-rinconada",
    "carmona",
    "coria-rio",
    "moron-frontera",
    "tomares",
    "san-juan-aznalfarache",
    "bormujos",
    "lebrija",
    "marchena",
    "osuna",
    "camas",
    "gines",
    "castilleja-cuesta",
    "espartinas",
    "bollullos-mitacion",
    "lora-rio",
    "alcala-rio",
    "gelves",
    "mairena-alcor",
    "brenes",
    "palomares-rio",
    "santiponce",
    "la-algaba",
    "valencina-concepcion",
    "arahal",
    "estepa",
    "el-viso-alcor",
    "las-cabezas-san-juan",
    "pilas",
    "guillena",
    "puebla-cazalla",
    "villanueva-ariscal",
    "sanlucar-mayor",
  ],
  granada: [
    "granada",
    "motril",
    "almunecar",
    "armilla",
    "maracena",
    "las-gabias",
    "loja",
    "baza",
    "guadix",
    "santa-fe",
    "atarfe",
    "albolote",
    "huetor-vega",
    "ogijares",
    "peligros",
    "pulianas",
    "la-zubia",
    "cenes-vega",
    "monachil",
    "salobrena",
    "chauchina",
    "fuente-vaqueros",
    "pinos-puente",
    "illora",
    "iznalloz",
    "durcal",
    "huetor-tajar",
    "cullar-vega",
    "otura",
    "churriana-vega",
    "vegas-genil",
    "la-herradura",
    "orgiva",
    "lanjaron",
    "alhama-granada",
    "montefrio",
  ],
  cordoba: [
    "cordoba",
    "lucena",
    "puente-genil",
    "montilla",
    "priego-cordoba",
    "cabra",
    "palma-rio",
    "baena",
    "pozoblanco",
    "penaroya-pueblonuevo",
    "aguilar-frontera",
    "la-carlota",
    "castro-rio",
    "rute",
    "villanueva-cordoba",
    "fernan-nunez",
    "monturque",
    "montemayor",
    "espejo",
    "bujalance",
    "carcabuey",
    "dona-mencia",
    "montoro",
    "hinojosa-duque",
  ],
  cadiz: [
    "cadiz",
    "jerez-frontera",
    "algeciras",
    "san-fernando",
    "el-puerto-santa-maria",
    "chiclana-frontera",
    "sanlucar-barrameda",
    "la-linea-concepcion",
    "puerto-real",
    "arcos-frontera",
    "rota",
    "los-barrios",
    "barbate",
    "conil-frontera",
    "ubrique",
    "tarifa",
    "medina-sidonia",
    "vejer-frontera",
    "chipiona",
    "jimena-frontera",
    "san-roque",
    "trebujena",
    "puerto-serrano",
    "bornos",
    "villamartin",
    "olvera",
    "grazalema",
    "zahara-sierra",
  ],
  almeria: [
    "almeria",
    "el-ejido",
    "roquetas-mar",
    "nijar",
    "aguadulce",
    "vicar",
    "adra",
    "huercal-overa",
    "vera",
    "garrucha",
    "mojacar",
    "cuevas-almanzora",
    "albox",
    "pulpi",
    "carboneras",
    "berja",
    "dalias",
    "huercal-almeria",
    "la-mojonera",
    "viator",
    "tabernas",
    "rioja",
    "alhama-almeria",
    "macael",
    "velez-rubio",
    "lubrin",
    "calahonda",
    "torrenueva-costa",
    "sorbas",
    "antas",
    "los-gallardos",
    "turre",
    "zurgena",
    "arboleas",
    "cantoria",
    "purchena",
    "olula-rio",
    "fines",
  ],
  huelva: [
    "huelva",
    "lepe",
    "almonte",
    "isla-cristina",
    "moguer",
    "ayamonte",
    "punta-umbria",
    "cartaya",
    "bollullos-par-condado",
    "aljaraque",
    "palma-condado",
    "palos-frontera",
    "san-juan-puerto",
    "trigueros",
    "valverde-camino",
    "nerva",
    "gibraleon",
    "bonares",
    "minas-riotinto",
    "villanueva-cruces",
    "aracena",
    "matalascanas",
    "cortegana",
    "rociana-condado",
    "zalamea-real",
  ],
  jaen: [
    "jaen",
    "linares",
    "andujar",
    "ubeda",
    "martos",
    "alcala-real",
    "baeza",
    "la-carolina",
    "jodar",
    "mancha-real",
    "torre-campo",
    "alcaudete",
    "bailen",
    "villacarrillo",
    "villanueva-arzobispo",
    "santisteban-puerto",
    "porcuna",
    "torredonjimeno",
    "mengíbar",
    "cazorla",
    "quesada",
    "pozo-alcon",
  ],

  // ============ COMUNIDAD VALENCIANA ============
  valencia: [
    "valencia",
    "torrent",
    "gandia",
    "paterna",
    "sagunto",
    "mislata",
    "burjassot",
    "ontinyent",
    "manises",
    "aldaia",
    "alfafar",
    "catarroja",
    "xirivella",
    "quart-poblet",
    "alzira",
    "xativa",
    "sueca",
    "cullera",
    "requena",
    "lliria",
    "algemesi",
    "alaquàs",
    "picassent",
    "oliva",
    "paiporta",
    "massanassa",
    "silla",
    "benetusser",
    "tavernes-blanques",
    "moncada",
    "alboraya",
    "godella",
    "rocafort",
    "betera",
    "pobla-vallbona",
    "riba-roja-turia",
    "utiel",
    "chiva",
    "bunol",
    "carlet",
    "alginet",
    "beniparrell",
    "albal",
    "sedavi",
    "pucol",
    "tavernes-valldigna",
    "carcaixent",
    "almussafes",
    "alcasser",
    "meliana",
    "picanya",
    "rafelbunyol",
  ],
  alicante: [
    "alicante",
    "elche",
    "torrevieja",
    "orihuela",
    "benidorm",
    "alcoy",
    "elda",
    "san-vicente-raspeig",
    "denia",
    "villena",
    "petrer",
    "crevillent",
    "villajoyosa",
    "novelda",
    "santa-pola",
    "ibi",
    "altea",
    "calpe",
    "muchamiel",
    "aspe",
    "campello",
    "san-juan-alicante",
    "javea",
    "alfaz-pi",
    "guardamar-segura",
    "pilar-horadada",
    "moraira",
    "teulada",
    "finestrat",
    "la-nucia",
    "albir",
    "rojales",
    "almoradi",
    "catral",
    "callosa-segura",
    "cox",
    "dolores",
    "rafal",
    "jijona",
    "monovar",
    "ondara",
    "pedreguer",
    "benissa",
    "pego",
    "gata-gorgos",
    "san-miguel-salinas",
    "los-montesinos",
    "san-fulgencio",
    "bigastro",
    "redovan",
    "benejuzar",
    "monforte-cid",
    "hondon-nieves",
    "daya-nueva",
    "orihuela-costa",
    "jacarilla",
    "algorfa",
    "benijofar",
    "san-isidro-alicante",
    "formentera-segura",
    "granja-rocamora",
    "dolores-alicante",
  ],
  castellon: [
    "castellon-plana",
    "vila-real",
    "burriana",
    "vinaros",
    "benicarlo",
    "onda",
    "almazora",
    "la-vall-uixo",
    "benicassim",
    "nules",
    "oropesa-mar",
    "segorbe",
    "betxi",
    "borriol",
    "lucena-cid",
    "alcora",
    "moncofar",
    "torreblanca",
    "peniscola",
    "alcala-xivert",
    "san-mateo",
  ],

  // ============ PAIS VASCO ============
  bizkaia: [
    "bilbao",
    "barakaldo",
    "getxo",
    "portugalete",
    "santurtzi",
    "basauri",
    "leioa",
    "galdakao",
    "durango",
    "erandio",
    "sestao",
    "gernika-lumo",
    "mungia",
    "amorebieta",
    "bermeo",
    "sopela",
    "algorta",
    "plentzia",
    "gorliz",
    "bakio",
    "berango",
    "loiu",
    "derio",
    "zamudio",
    "arrigorriaga",
    "zaratamo",
    "etxebarri",
    "ondarroa",
  ],
  gipuzkoa: [
    "san-sebastian",
    "irun",
    "errenteria",
    "donostia",
    "eibar",
    "zarautz",
    "hernani",
    "tolosa",
    "arrasate",
    "hondarribia",
    "lasarte-oria",
    "pasaia",
    "azpeitia",
    "azkoitia",
    "bergara",
    "andoain",
    "beasain",
    "zumarraga",
    "legazpi",
    "urnieta",
    "oiartzun",
    "usurbil",
    "getaria",
    "zumaia",
    "deba",
    "mutriku",
    "ordizia",
    "elgoibar",
    "onati",
  ],
  araba: [
    "vitoria-gasteiz",
    "llodio",
    "amurrio",
    "salvatierra",
    "oyón",
    "labastida",
    "laguardia",
    "alegria-dulantzi",
    "santa-cruz-campezo",
    "araia",
  ],

  // ============ GALICIA ============
  a_coruna: [
    "a-coruna",
    "santiago-compostela",
    "ferrol",
    "naron",
    "oleiros",
    "arteixo",
    "carballo",
    "culleredo",
    "cambre",
    "ames",
    "riveira",
    "boiro",
    "betanzos",
    "sada",
    "noia",
    "cee",
    "muxia",
    "fisterra",
    "muros",
    "porto-son",
    "rianxo",
    "padron",
    "ordes",
    "melide",
    "arzua",
    "curtis",
    "teo",
    "brion",
    "carino",
    "cedeira",
    "ares",
    "mugardos",
    "fene",
    "cabanas",
    "pontedeume",
    "mino",
    "oroso",
    "vedra",
    "boqueixon",
    "touro",
  ],
  pontevedra: [
    "vigo",
    "pontevedra",
    "vilagarcia-arousa",
    "redondela",
    "marin",
    "cangas",
    "moana",
    "ponteareas",
    "lalin",
    "porriño",
    "tui",
    "sanxenxo",
    "cambados",
    "o-grove",
    "nigran",
    "baiona",
    "gondomar",
    "mos",
    "salceda-caselas",
    "bueu",
    "a-guarda",
    "poio",
    "caldas-reis",
    "vilanova-arousa",
    "ribadumia",
    "a-estrada",
    "vilaboa",
    "tomiño",
    "meaño",
  ],
  ourense: [
    "ourense",
    "verin",
    "o-barco-valdeorras",
    "carballino",
    "xinzo-limia",
    "allariz",
    "ribadavia",
    "o-pereiro-aguiar",
    "coles",
    "maceda",
    "celanova",
    "a-rua",
    "o-carballiño",
    "bande",
    "leiro",
    "castrelo-miño",
  ],
  lugo: [
    "lugo",
    "monforte-lemos",
    "viveiro",
    "vilalba",
    "sarria",
    "foz",
    "ribadeo",
    "burela",
    "chantada",
    "guitiriz",
    "xove",
    "cervo",
    "mondoñedo",
    "ourol",
  ],

  // ============ CASTILLA Y LEON ============
  valladolid: [
    "valladolid",
    "laguna-duero",
    "medina-campo",
    "arroyo-encomienda",
    "tordesillas",
    "tudela-duero",
    "simancas",
    "cigales",
    "zaratán",
    "boecillo",
    "aldeamayor-san-martin",
    "peñafiel",
    "íscar",
    "olmedo",
    "portillo",
    "mojados",
    "villabáñez",
    "medina-rioseco",
  ],
  burgos: [
    "burgos",
    "miranda-ebro",
    "aranda-duero",
    "briviesca",
    "medina-pomar",
    "villarcayo",
    "lerma",
    "salas-infantes",
    "roa",
    "belorado",
    "pradoluengo",
    "espinosa-monteros",
    "villagonzalo-pedernales",
  ],
  leon: [
    "leon",
    "ponferrada",
    "san-andres-rabanedo",
    "villaquilambre",
    "astorga",
    "la-bañeza",
    "bembibre",
    "villablino",
    "cacabelos",
    "camponaraya",
    "valencia-don-juan",
    "cistierna",
    "boñar",
    "la-robla",
    "santa-maria-paramo",
    "benavides-orbigo",
    "la-virgen-camino",
    "veguellina-orbigo",
    "sahagun",
    "la-pola-gordon",
  ],
  salamanca: [
    "salamanca",
    "santa-marta-tormes",
    "bejar",
    "ciudad-rodrigo",
    "villamayor",
    "carbajosa-sagrada",
    "peñaranda-bracamonte",
    "guijuelo",
    "alba-tormes",
    "ledesma",
  ],
  zamora: ["zamora", "benavente", "toro", "morales-vino", "puebla-sanabria", "fuentesaúco", "corrales-vino", "villalpando"],
  palencia: ["palencia", "aguilar-campoo", "guardo", "venta-baños", "villamuriel-cerrato", "dueñas-palencia", "cervera-pisuerga"],
  segovia: ["segovia", "cuellar", "el-espinar", "san-ildefonso", "cantalejo", "carbonero-mayor", "riaza"],
  soria: ["soria", "almazan", "el-burgo-osma", "san-esteban-gormaz", "agreda", "olvega"],
  avila: ["avila", "arevalo", "las-navas-marques", "candeleda", "el-barco-avila", "el-tiemblo", "arenas-san-pedro"],

  // ============ CASTILLA-LA MANCHA ============
  toledo: [
    "toledo",
    "talavera-reina",
    "illescas",
    "seseña",
    "yuncos",
    "fuensalida",
    "madridejos",
    "mora",
    "consuegra",
    "sonseca",
    "ocaña",
    "villacañas",
    "quintanar-orden",
    "torrijos",
    "bargas",
    "olias-rey",
    "nambroca",
    "tembleque",
    "escalona",
    "la-puebla-montalban",
  ],
  ciudad_real: [
    "ciudad-real",
    "puertollano",
    "tomelloso",
    "alcazar-san-juan",
    "valdepeñas",
    "manzanares",
    "daimiel",
    "la-solana",
    "miguelturra",
    "bolaños-calatrava",
    "socuellamos",
    "campo-criptana",
    "villanueva-infantes",
    "almaden",
    "herencia",
    "almagro",
    "argamasilla-alba",
    "calzada-calatrava",
  ],
  albacete: [
    "albacete",
    "hellin",
    "villarrobledo",
    "almansa",
    "la-roda",
    "caudete",
    "tobarra",
    "casas-ibanez",
    "madrigueras",
    "tarazona-mancha",
    "chinchilla-monte-aragon",
  ],
  guadalajara: [
    "guadalajara",
    "azuqueca-henares",
    "alovera",
    "el-casar",
    "cabanillas-campo",
    "marchamalo",
    "villanueva-torre",
    "siguenza",
    "molina-aragon",
    "brihuega",
    "pastrana",
    "mondejar",
  ],
  cuenca: [
    "cuenca",
    "tarancon",
    "san-clemente",
    "motilla-palancar",
    "quintanar-rey",
    "las-pedroñeras",
    "mota-cuervo",
    "iniesta",
    "honrubia",
    "villamayor-santiago",
    "belmonte",
  ],

  // ============ ARAGON ============
  zaragoza: [
    "zaragoza",
    "calatayud",
    "utebo",
    "ejea-caballeros",
    "tarazona",
    "caspe",
    "la-almunia-doña-godina",
    "cuarte-huerva",
    "zuera",
    "illueca",
    "maria-huerva",
    "fuentes-ebro",
    "alagón",
    "borja",
    "alfajarin",
    "villanueva-gállego",
    "cadrete",
    "sos-rey-catolico",
    "gallur",
    "la-puebla-alfinden",
  ],
  huesca: [
    "huesca",
    "monzón",
    "barbastro",
    "jaca",
    "fraga",
    "sabiñánigo",
    "binéfar",
    "tamarite-litera",
    "graus",
    "almudevar",
    "ayerbe",
    "sariñena",
    "alquezar",
    "ainsa",
  ],
  teruel: [
    "teruel",
    "alcañiz",
    "andorra",
    "calamocha",
    "utrillas",
    "montalban",
    "albarracin",
    "mora-rubielos",
    "cella",
    "calanda",
    "valderrobres",
    "alcorisa",
  ],

  // ============ MURCIA ============
  murcia: [
    "murcia",
    "cartagena",
    "lorca",
    "molina-segura",
    "alcantarilla",
    "mazarron",
    "cieza",
    "aguilas",
    "yecla",
    "jumilla",
    "torre-pacheco",
    "san-javier",
    "san-pedro-pinatar",
    "los-alcazares",
    "las-torres-cotillas",
    "totana",
    "alhama-murcia",
    "la-union",
    "archena",
    "mula",
    "caravaca-cruz",
    "calasparra",
    "bullas",
    "ceutí",
    "lorquí",
    "alguazas",
    "beniel",
    "santomera",
    "la-manga",
    "fuente-alamo",
    "abaran",
    "cehegin",
    "fortuna",
    "puerto-lumbreras",
  ],

  // ============ ISLAS BALEARES ============
  baleares: [
    "palma",
    "calvia",
    "ibiza",
    "manacor",
    "llucmajor",
    "marratxi",
    "inca",
    "santa-eulalia-rio",
    "sant-josep-sa-talaia",
    "alcudia",
    "felanitx",
    "mahon",
    "ciutadella-menorca",
    "pollença",
    "soller",
    "sant-llorenç-cardassar",
    "sant-antoni-portmany",
    "muro",
    "campos",
    "santanyi",
    "santa-margalida",
    "sa-pobla",
    "binissalem",
    "arta",
    "capdepera",
    "son-servera",
    "cala-millor",
    "andratx",
    "porto-cristo",
    "cala-ratjada",
    "can-picafort",
    "puerto-pollensa",
    "puerto-alcudia",
    "paguera",
    "cala-dor",
    "santa-ponsa",
  ],

  // ============ ISLAS CANARIAS ============
  las_palmas: [
    "las-palmas-gran-canaria",
    "telde",
    "santa-lucia-tirajana",
    "arrecife",
    "san-bartolome-tirajana",
    "playa-ingles",
    "aguimes",
    "ingenio",
    "galdar",
    "arucas",
    "mogan",
    "puerto-rosario",
    "tias",
    "la-oliva",
    "pajara",
    "tuineje",
    "antigua",
    "teror",
    "firgas",
    "valsequillo",
    "tejeda",
    "maspalomas",
    "puerto-rico",
    "playa-blanca",
    "costa-teguise",
    "corralejo",
    "caleta-fuste",
  ],
  tenerife: [
    "santa-cruz-tenerife",
    "san-cristobal-laguna",
    "arona",
    "adeje",
    "la-orotava",
    "granadilla-abona",
    "puerto-cruz",
    "los-realejos",
    "tacoronte",
    "candelaria",
    "guia-isora",
    "icod-vinos",
    "santiago-teide",
    "guimar",
    "el-rosario",
    "tegueste",
    "la-victoria-acentejo",
    "san-miguel-abona",
    "vilaflor",
    "arico",
    "costa-adeje",
    "playa-americas",
    "los-cristianos",
    "los-gigantes",
    "el-medano",
    "santa-cruz-palma",
    "los-llanos-aridane",
    "san-sebastian-gomera",
    "valle-gran-rey",
    "valverde",
    "brena-baja",
    "tazacorte",
  ],

  // ============ ASTURIAS ============
  asturias: [
    "gijon",
    "oviedo",
    "aviles",
    "siero",
    "langreo",
    "mieres",
    "castrillon",
    "san-martin-rey-aurelio",
    "corvera-asturias",
    "llanera",
    "villaviciosa",
    "llanes",
    "cangas-onis",
    "navia",
    "luarca",
    "pravia",
    "grado",
    "tineo",
    "cangas-narcea",
    "laviana",
    "aller",
    "lena",
    "ribadesella",
    "colunga",
    "cudillero",
    "tapia-casariego",
    "pola-lena",
    "luanco",
    "candas",
    "salinas-asturias",
    "piedras-blancas",
    "posada-llanes",
  ],

  // ============ CANTABRIA ============
  cantabria: [
    "santander",
    "torrelavega",
    "castro-urdiales",
    "camargo",
    "piélagos",
    "el-astillero",
    "laredo",
    "santa-cruz-bezana",
    "santoña",
    "colindres",
    "reinosa",
    "suances",
    "noja",
    "comillas",
    "san-vicente-barquera",
    "ramales-victoria",
    "medio-cudeyo",
    "marina-cudeyo",
    "ribamontán-mar",
    "bareyo",
    "potes",
    "ampuero",
    "cabezon-sal",
  ],

  // ============ NAVARRA ============
  navarra: [
    "pamplona",
    "tudela",
    "barañain",
    "burlada",
    "estella-lizarra",
    "zizur-mayor",
    "tafalla",
    "ansoain",
    "villava",
    "berriozar",
    "huarte",
    "noain",
    "cintruénigo",
    "corella",
    "sangüesa",
    "peralta",
    "alsasua",
    "elizondo",
    "baztan",
    "lodosa",
    "olite",
    "viana",
    "carcastillo",
    "caparroso",
    "ochagavia",
    "roncesvalles",
  ],

  // ============ LA RIOJA ============
  la_rioja: [
    "logroño",
    "calahorra",
    "arnedo",
    "haro",
    "lardero",
    "villamediana-iregua",
    "najera",
    "alfaro",
    "santo-domingo-calzada",
    "autol",
    "rincon-soto",
    "aldeanueva-ebro",
    "ezcaray",
  ],

  // ============ EXTREMADURA ============
  badajoz: [
    "badajoz",
    "merida",
    "don-benito",
    "almendralejo",
    "villanueva-serena",
    "zafra",
    "montijo",
    "villafranca-barros",
    "olivenza",
    "jerez-caballeros",
    "azuaga",
    "llerena",
    "castuera",
    "fregenal-sierra",
    "santos-maimona",
  ],
  caceres: [
    "caceres",
    "plasencia",
    "navalmoral-mata",
    "coria",
    "trujillo",
    "miajadas",
    "talayuela",
    "moraleja",
    "arroyo-luz",
    "jaraiz-vera",
    "montehermoso",
    "hervas",
  ],

  // ============ CEUTA Y MELILLA ============
  ceuta_melilla: [
    "ceuta",
    "melilla",
  ],
}

export function getAllCities(): string[] {
  return Object.values(CITIES_SPAIN).flat()
}

// Helper to get city display name
export function getCityDisplayName(slug: string): string {
  let decodedSlug = slug
  try { decodedSlug = decodeURIComponent(slug) } catch {}
  return decodedSlug
  .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ")
    .replace("Llobregat", "de Llobregat")
    .replace("Valles", "del Vallès")
    .replace(" Mar", " de Mar")
    .replace("Emporda", "d'Empordà")
    .replace("Selva", "de la Selva")
    .replace("Camp", "del Camp")
    .replace(" Frontera", " de la Frontera")
    .replace("Playa Ingles", "Playa del Inglés")
    .replace(" Henares", " de Henares")
    .replace(" Reina", " de la Reina")
    .replace(" Segura", " del Segura")
}

// Helper to get region from city
export function getCityRegion(citySlug: string): string {
  let decodedSlug = citySlug
  try { decodedSlug = decodeURIComponent(citySlug) } catch {}
  for (const [region, cities] of Object.entries(CITIES_SPAIN)) {
  if (cities.includes(decodedSlug)) {
      const regionNames: Record<string, string> = {
        barcelona: "Barcelona",
        girona: "Girona",
        tarragona: "Tarragona",
        lleida: "Lleida",
        madrid: "Madrid",
        malaga: "Málaga",
        sevilla: "Sevilla",
        granada: "Granada",
        cordoba: "Córdoba",
        cadiz: "Cádiz",
        almeria: "Almería",
        huelva: "Huelva",
        jaen: "Jaén",
        valencia: "Valencia",
        alicante: "Alicante",
        castellon: "Castellón",
        bizkaia: "Bizkaia",
        gipuzkoa: "Gipuzkoa",
        araba: "Álava",
        a_coruna: "A Coruña",
        pontevedra: "Pontevedra",
        ourense: "Ourense",
        lugo: "Lugo",
        valladolid: "Valladolid",
        burgos: "Burgos",
        leon: "León",
        salamanca: "Salamanca",
        zamora: "Zamora",
        palencia: "Palencia",
        segovia: "Segovia",
        soria: "Soria",
        avila: "Ávila",
        toledo: "Toledo",
        ciudad_real: "Ciudad Real",
        albacete: "Albacete",
        guadalajara: "Guadalajara",
        cuenca: "Cuenca",
        zaragoza: "Zaragoza",
        huesca: "Huesca",
        teruel: "Teruel",
        murcia: "Murcia",
        baleares: "Islas Baleares",
        las_palmas: "Las Palmas",
        tenerife: "Tenerife",
        asturias: "Asturias",
        cantabria: "Cantabria",
        navarra: "Navarra",
        la_rioja: "La Rioja",
        badajoz: "Badajoz",
        caceres: "Cáceres",
        ceuta_melilla: "Ceuta y Melilla",
      }
      return regionNames[region] || region.charAt(0).toUpperCase() + region.slice(1)
    }
  }
  return "España"
}

// Alias for backward compatibility
export const getCityProvince = getCityRegion
